INSERT INTO Consonants(consonant_id, consonant, english_pronounciation, audio_path) VALUES 
  (1, "ক", 0, "k", "alphabet_audios/consonants/1.wav"),
  (2, "খ", 0, "kh", "alphabet_audios/consonants/2.wav"),
  (3, "গ", 0, "g", "alphabet_audios/consonants/3.wav"),
  (4, "ঘ", 0, "gh", "alphabet_audios/consonants/4.wav"),
  (5, "ঙ", 0, "gn", "alphabet_audios/consonants/5.wav"),
  (6, "চ", 0, "ch", "alphabet_audios/consonants/6.wav"),
  (7, "ছ", 0, "chh", "alphabet_audios/consonants/7.wav"),
  (8, "জ", 0, "j", "alphabet_audios/consonants/8.wav"),
  (9, "ঝ", 0, "jh", "alphabet_audios/consonants/9.wav"),
  (10,"ঞ", 0, "n", "alphabet_audios/consonants/10.wav"),
  (11, "ট", 0, "t", "alphabet_audios/consonants/11.wav"),
  (12, "ঠ", 0, "th", "alphabet_audios/consonants/12.wav"),
  (13, "ড", 0, "d", "alphabet_audios/consonants/13.wav"),
  (14, "ঢ", 0, "dh", "alphabet_audios/consonants/14.wav"), 
  (15, "ণ", 0, "n", "alphabet_audios/consonants/15.wav"),
  (16, "ত", 0, "t", "alphabet_audios/consonants/16.wav"),
  (17, "থ", 0, "th", "alphabet_audios/consonants/17.wav"),
  (18, "দ", 0, "d", "alphabet_audios/consonants/18.wav"),
  (19, "ধ", 0, "dh", "alphabet_audios/consonants/19.wav"),
  (20, "ন", 0, "n", "alphabet_audios/consonants/20.wav"),
  (21, "প", 0, "p", "alphabet_audios/consonants/21.wav"),
  (22, "ফ", 0, "f", "alphabet_audios/consonants/22.wav"),
  (23, "ব", 0, "b", "alphabet_audios/consonants/23.wav"),
  (24, "ভ", 0, "bh", "alphabet_audios/consonants/24.wav"),
  (25, "ম", 0, "m", "alphabet_audios/consonants/25.wav"),
  (26, "য", 0, "j", "alphabet_audios/consonants/26.wav"),
  (27, "র", 0, "r", "alphabet_audios/consonants/27.wav"),
  (28, "ল", 0, "l", "alphabet_audios/consonants/28.wav"),
  (29, "শ", 0, "sh", "alphabet_audios/consonants/29.wav"),
  (30, "ষ", 0, "sh", "alphabet_audios/consonants/30.wav"),
  (31, "স", 0, "s/sh", "alphabet_audios/consonants/31.wav"),
  (32, "হ", 0, "h", "alphabet_audios/consonants/32.wav"),
  (33, "য়", 0, "y", "alphabet_audios/consonants/33.wav"),
  (34, "ড়", 0, "r", "alphabet_audios/consonants/34.wav"),
  (35, "ঢ়", 0, "rh", "alphabet_audios/consonants/35.wav"),
  (36, "ৎ", 0, "idk", "alphabet_audios/consonants/36.wav"),
  (37, " ং", 0, "ng", "alphabet_audios/consonants/37.wav"),
  (38, " ঃ", 0, "idk", "alphabet_audios/consonants/38.wav"),
  (39, " ঁ", 0, "idk", "alphabet_audios/consonants/39.wav");

INSERT INTO Vowels(vowel_id, vowel, english_pronounciation, diacritic, audio_path) VALUES
  (1, "অ", "a", "alphabet_audios/vowels/1.wav"),
  (2, "আ", "aa", "া", "alphabet_audios/vowels/2.wav"),
  (3, "ই", "e", " ি", "alphabet_audios/vowels/3.wav"),
  (4, "ঈ", "ee", " ী", "alphabet_audios/vowels/4.wav"),
  (5, "উ", "u", " ু", "alphabet_audios/vowels/5.wav"),
  (6, "ঊ", "uu", " ূ", "alphabet_audios/vowels/6.wav"), 
  (7, "ঋ", "idk", "alphabet_audios/vowels/7.wav"), 
  (8, "এ", "ay", " ে", "alphabet_audios/vowels/8.wav"), 
  (9, "ঐ", "ayy", " ৈ", "alphabet_audios/vowels/9.wav"), 
  (10, "ও", "ou", " ো", "alphabet_audios/vowels/10.wav"), 
  (11, "ঔ", "ouu", " ৌ", "alphabhet_audios/vowels/11.wav");
  