USE fahmed$banglalearning;

INSERT INTO Consonants(consonant_id, consonant, english_pronounciation, audio_path) VALUES 
  (1, "ক", "k", "alphabet_audios/consonants/1.wav"),
  (2, "খ", "kh", "alphabet_audios/consonants/2.wav"),
  (3, "গ", "g", "alphabet_audios/consonants/3.wav"),
  (4, "ঘ", "gh", "alphabet_audios/consonants/4.wav"),
  (5, "ঙ", "gn", "alphabet_audios/consonants/5.wav"),
  (6, "চ", "ch", "alphabet_audios/consonants/6.wav"),
  (7, "ছ", "chh", "alphabet_audios/consonants/7.wav"),
  (8, "জ", "j", "alphabet_audios/consonants/8.wav"),
  (9, "ঝ", "jh", "alphabet_audios/consonants/9.wav"),
  (10,"ঞ", "n", "alphabet_audios/consonants/10.wav"),
  (11, "ট", "t", "alphabet_audios/consonants/11.wav"),
  (12, "ঠ", "th", "alphabet_audios/consonants/12.wav"),
  (13, "ড", "d", "alphabet_audios/consonants/13.wav"),
  (14, "ঢ", "dh", "alphabet_audios/consonants/14.wav"), 
  (15, "ণ", "n", "alphabet_audios/consonants/15.wav"),
  (16, "ত", "t", "alphabet_audios/consonants/16.wav"),
  (17, "থ", "th", "alphabet_audios/consonants/17.wav"),
  (18, "দ", "d", "alphabet_audios/consonants/18.wav"),
  (19, "ধ", "dh", "alphabet_audios/consonants/19.wav"),
  (20, "ন", "n", "alphabet_audios/consonants/20.wav"),
  (21, "প", "p", "alphabet_audios/consonants/21.wav"),
  (22, "ফ", "f", "alphabet_audios/consonants/22.wav"),
  (23, "ব", "b", "alphabet_audios/consonants/23.wav"),
  (24, "ভ", "bh", "alphabet_audios/consonants/24.wav"),
  (25, "ম", "m", "alphabet_audios/consonants/25.wav"),
  (26, "য", "j", "alphabet_audios/consonants/26.wav"),
  (27, "র", "r", "alphabet_audios/consonants/27.wav"),
  (28, "ল", "l", "alphabet_audios/consonants/28.wav"),
  (29, "শ", "sh", "alphabet_audios/consonants/29.wav"),
  (30, "ষ", "sh", "alphabet_audios/consonants/30.wav"),
  (31, "স", "s/sh", "alphabet_audios/consonants/31.wav"),
  (32, "হ", "h", "alphabet_audios/consonants/32.wav"),
  (33, "য়", "y", "alphabet_audios/consonants/33.wav"),
  (34, "ড়", "r", "alphabet_audios/consonants/34.wav"),
  (35, "ঢ়", "rh", "alphabet_audios/consonants/35.wav"),
  (36, "ৎ", "idk", "alphabet_audios/consonants/36.wav"),
  (37, " ং", "ng", "alphabet_audios/consonants/37.wav"),
  (38, " ঃ", "idk", "alphabet_audios/consonants/38.wav"),
  (39, " ঁ", "idk", "alphabet_audios/consonants/39.wav");

INSERT INTO Vowels(vowel_id, vowel, english_pronounciation, diacritic, audio_path) VALUES
  (1, "অ", "a", "n/a", "alphabet_audios/vowels/1.wav"),
  (2, "আ", "aa", "া", "alphabet_audios/vowels/2.wav"),
  (3, "ই", "e", " ি", "alphabet_audios/vowels/3.wav"),
  (4, "ঈ", "ee", " ী", "alphabet_audios/vowels/4.wav"),
  (5, "উ", "u", " ু", "alphabet_audios/vowels/5.wav"),
  (6, "ঊ", "uu", " ূ", "alphabet_audios/vowels/6.wav"), 
  (7, "ঋ", "idk", "idk", "alphabet_audios/vowels/7.wav"), 
  (8, "এ", "ay", " ে", "alphabet_audios/vowels/8.wav"), 
  (9, "ঐ", "ayy", " ৈ", "alphabet_audios/vowels/9.wav"), 
  (10, "ও", "ou", " ো", "alphabet_audios/vowels/10.wav"), 
  (11, "ঔ", "ouu", " ৌ", "alphabhet_audios/vowels/11.wav");
  